version: "3.7"

services:
  ngrok:
    image: wernight/ngrok
    container_name: code-server_ngrok
    ports:
      - "0.0.0.0:80:4040"
    depends_on:
      - server
    environment:
      NGROK_PORT: server:8080

  server:
    container_name: coder-server_server
    build:
      context: ./containers/code-server
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PROJECTS_PATH}:${PROJECTS_PATH}
      - ${HOME}/.gitconfig:/home/coder/.gitconfig
      - ${HOME}/.ssh":/home/coder/.ssh
      - ${HOME}/.vscode/extensions:/home/coder/.local/share/code-server/extensions
      - code-server:/home/coder/.local/share/code-server

volumes:
  code-server:
